config/routes.rb
Rails.application.routes.draw do
  post 'callback', to: 'collaboration_callbacks#confirm_url'
  delete 'callback', to: 'collaboration_callbacks#confirm_url'

  resources :tool_proxy, only: [:create]

  get 'launch', to: 'message#xml_config', as: :xml_config
  post 'launch', to: 'message#launch_request', as: 'recordrtc_launch'
  post 'messages/content-item', to: 'message#content_item_selection', as: 'content_item_request_launch'
  post 'messages/content-item', to: 'message#launch_request', as: 'content_item_launch'
  post 'messages/signed_content_item_request', to: 'message#signed_content_item_request'
  post 'messages/youtube', to: 'message#youtube', as: 'youtube'

  post 'register', to: 'registration#register', as: :tool_registration
  post 'reregister', to: 'registration#register', as: :tool_reregistration
  post 'submit_capabilities', to: 'registration#save_capabilities', as: 'save_capabilities'
  get 'submit_proxy/:registration_uuid', to: 'registration#submit_proxy', as: 'submit_proxy'

  mount RailsLti2Provider::Engine => '/rails_lti2_provider'

  namespace :api, defaults: {format: :json} do
    resources :recordings, except: [:new, :edit]
  end

  resources :record, only: [:index, :show, :new, :edit]

  get 'refresh_recordings', to: 'record#refresh_recordings'
end

app/controllers/recordrtc_controller.rb
class RecordRTCController < ApplicationController
  before_action :set_account
  before_action :set_recording, except: [:index, :new, :refresh_recordings]

  # GET /recordrtc
  def index
    @full_name = session[:full_name]

    @recordings = @account.recordings
  end

  # GET /recordrtc/:id
  def show
  end

  # GET /recordrtc/new
  def new
    @recording = @account.recordings.new
  end

  # GET /recordrtc/:id/edit
  def edit
  end

  def refresh_recordings
    @recordings = @account.recordings

    respond_to do |format|
      format.js
    end
  end

  private
  def set_account
    @account = Account.find_or_create_by!(user_id: session[:user_id])
  end

  def set_recording
    @recording = @account.recordings.find(params[:id])
  end
end

app/views/recordrtc/_recordings.html.erb
<% if @recordings.empty? %>
  There's nothing here! <%= link_to 'Click here', new_recordrtc_path %> to add a new recording.
<% end %>

<% unless @recordings.empty? %>
  <table id="recordings-table" class="table table-striped table-bordered dataTable no-footer responsive nowrap" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th>Title</th>
        <th>Uploaded</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @recordings.each do |rec| %>
        <tr>
          <td><%= link_to rec.title, recordrtc_path(rec) %></td>
          <td><%= rec.created_at.strftime("%A, %d %b %Y @ %H:%M") %></td>
          <td class="text-right">
            <div class="btn-group">
              <%= link_to '<i class="fa fa-pencil-square-o"></i> Edit'.html_safe, edit_recordrtc_path(rec), class: 'btn btn-default btn-xs', method: :get %>
              <%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, api_recording_path(rec), class: 'delete-btn btn btn-outline btn-danger btn-xs', method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/recordrtc/edit.html.erb
<% content_for :page_header do %>
  Edit Recording Information
<% end %>

<% content_for :panel_heading do %>
  <strong><%= @recording.title %></strong>
<% end %>

<div class="row">
  <div class="col-lg-6">
    <div class="embed-responsive embed-responsive-4by3">
      <video src="<%= @recording.video.url %>" controls></video>
    </div>
  </div>

  <div class="col-lg-6">
    <%= form_for @recording, url: {controller: 'api/recordings', action: 'update'}, method: :put, remote: true do |f| %>
      <div id="title-box" class="form-group">
        <%= f.label :title %>:
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div id="description-box" class="form-group">
        <%= f.label :description %>:
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <%= f.button '<i class="fa fa-upload"></i> Update Recording'.html_safe, type: :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<br />

<%= link_to '<i class="fa fa-caret-left"></i> Back'.html_safe, recordrtc_index_path, id: 'back' %>

<!-- Modal -->
<div class="modal fade" id="updated-alert" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Success</h4>
      </div>
      <div class="modal-body">
        Your recording has been updated!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline btn-success" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<button id="show-modal" data-toggle="modal" data-target="#updated-alert"></button>
<!-- ./Modal -->

app/views/recordrtc/index.html.erb
<% content_for :page_header do %>
  <%= @full_name %>
<% end %>

<% content_for :panel_heading do %>
  <strong>Recordings</strong>
<% end %>

<div class="row">
  <div class="col-lg-12">
    <div id="browser-version-alert" class="alert alert-warning alert-dismissable">
        <button id="close-alert" type="button" class="close" data-dismiss="alert">&times;</button>
        <span class="alert-link">Browser Compatibility Warning</span>. For best results, please consider switching to Firefox &ge; 29, Chrome &ge; 49, or Opera &ge; 36.
    </div>
  </div>
</div>

<div id="recordings" class="panel-body">
  <%= render 'recordings' %>
</div>

<%= link_to '<i class="fa fa-times"></i> Close'.html_safe, '_self', id: 'close' %>

app/views/recordrtc/new.html.erb
<% content_for :page_header do %>
  Record Yourself!
<% end %>

<% content_for :panel_heading do %>
  <strong>Click "Start Recording" to begin</strong>
<% end %>

<div class="row">
  <div class="col-lg-6">
    <div class="embed-responsive embed-responsive-4by3">
      <video id="video-player" autoplay muted></video>
    </div>
  </div>

  <div class="col-lg-6">
    <button id="start-stop" class="btn btn-block btn-outline btn-danger"><i class="fa fa-circle"></i> Start Recording</button>

    <br />

    <div id="upload-form">
      <div class="form-group">
        <label for="title">Title:</label>
        <input name="title" id="title" class="form-control" />
      </div>

      <div class="form-group">
        <label for="description">Description:</label>
        <textarea name="description" id="description" class="form-control"></textarea>
      </div>

      <input type="hidden" name="account_id" id="account_id" value="<%= @account.id %>" />

      <button id="upload" class="btn btn-primary ladda-button" data-style="expand-right"><span class="ladda-label"><i class="fa fa-upload"></i> Save Recording</span></button>
    </div>
  </div>
</div>

<br />

<%= link_to '<i class="fa fa-caret-left"></i> Back'.html_safe, recordrtc_index_path, id: 'back' %>

<!-- Modal -->
<div class="modal fade" id="updated-alert" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Success</h4>
      </div>
      <div class="modal-body">
        Your recording has been saved!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline btn-success" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<button id="show-modal" data-toggle="modal" data-target="#updated-alert"></button>
<!-- ./Modal -->

app/views/recordrtc/show.html.erb
<% content_for :page_header do %>
  View Recording
<% end %>

<% content_for :panel_heading do %>
  <strong><%= @recording.title %></strong>
<% end %>

<div class="row">
  <div class="col-lg-6">
    <div class="embed-responsive embed-responsive-4by3">
      <video src="<%= @recording.video.url %>" controls></video>
    </div>
  </div>

  <div id="description-div" class="col-lg-6">
    <h5><strong>Description</strong></h5>
    <p><%= @recording.description %></p>
    <br />
    <p><i class="fa fa-clock-o fa-fw"></i> Uploaded at <%= @recording.created_at.strftime("%H:%M, on %d/%m/%Y") %></p>
    <p><i class="fa fa-pencil-square fa-fw"></i> Last edited at <%= @recording.updated_at.strftime("%H:%M, on %d/%m/%Y") %></p>

    <br />

    <%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, api_recording_path(@recording), id: 'delete-btn', class: 'btn btn-block btn-outline btn-danger', method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

<br />

<%= link_to '<i class="fa fa-caret-left"></i> Back'.html_safe, recordrtc_index_path, id: 'back' %>